### ISSUE TITLE
Max Hit bug

### ISSUE THREAD

**Issue by adnapPanda** [Maurits825/osrs-damage-sim#17]
![what](https://user-images.githubusercontent.com/47595365/216321319-4996b560-5d1d-45a4-93f0-5c66fb79eb5d.PNG)

**Comment by Maurits825** [comment]
fixed [07aaaf1](https://github.com/Maurits825/osrs-damage-sim/commit/07aaaf1fc4071e76a3c88b4bbdb5d726509695ba)
